### ISSUE TITLE
Maven publishing

### ISSUE THREAD

**Issue by Doomsdayrs** [korlibs/korge-luak#6]
The `maven-publish` plugin is missing, meaning this library cannot be easy installed.

**Comment by soywiz** [comment]
What's your specific use-case for it?

This korge-luak project is exposed via [kproject](https://docs.korge.org/kproject/) instead of maven-publish.
You can use it by adding a few lines of code to the `settings.gradle.kts` and `build.gradle.kts` as explained here: <https://docs.korge.org/kproject/#usage>

Could you try to use kproject instead of maven?

**Comment by Doomsdayrs** [comment]
> What's your specific use-case for it?

https://shosetsu.app/ uses Lua extensions, currently relying on the ancient luaj libraries. I want to swap to LuaK to enable cross platform support.

> Could you try to use kproject instead of maven?

Why would I use a non-standard implementation that only offers me libraries that are present under korlibs (which I do have a use for).

**Comment by soywiz** [comment]
I see. Thanks for the explanation. This specific repository is not published to central but can be consumed via kproject.

If you want to use maven pre-compiled artifacts or maven for this specific project, you can use an old version that was published to central before here:
https://central.sonatype.com/artifact/com.soywiz.korlibs.luak/luak/4.0.0-alpha-2
You can also fork it or include a git submodule and publish to maven yourself too.

**Comment by Doomsdayrs** [comment]
> This specific repository is not published to central but can be consumed via kpr

That is not quite what I want, enabling the `maven-publish` plugin allows users to install it locally or on their own maven instances.

I do not think this would be difficult to implement for you, as you know your own software stack. Allowing developers to use the library both via maven and kproject.

**Comment by soywiz** [comment]
Are you proposing to add the maven-publish plugin to the root build.gradle.kts that includes the example+library? Or to the library itself? The library doesn't include a build.gradle file itself since it is generated by kproject. I could apply that plugin in kproject, but kproject would still be required.

**Comment by JochenGuckSnk** [comment]
What is the blocker which prevents the general publikation to a maven repo? Im interested in just having the up to date implementation via maven.

**Comment by DersWasTaken** [comment]
Maven Publishing is not up to date on Maven Central. Is it possible to update so I can use the library standalone?

**Comment by soywiz** [comment]
This repo accepts PRs. But in any case, the `Add Maven Publish` PR wasn't there so it could be already used with jitpack? https://jitpack.io/

**Comment by DersWasTaken** [comment]
Jitpack also does not build, I should have mentioned that. My apologies

**Comment by DersWasTaken** [comment]
https://jitpack.io/com/github/korlibs/korge-luak/8b8e9619d8/build.log
